/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PracticeRouteRouteImport } from './routes/practice/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice/index'
import { Route as PracticeFormSimpleRouteImport } from './routes/practice/form-simple'
import { Route as PracticeDashboardRouteImport } from './routes/practice/dashboard'
import { Route as PracticeCounterRouteImport } from './routes/practice/counter'
import { Route as PracticePostsIndexRouteImport } from './routes/practice/posts/index'
import { Route as PracticeAttachfileIndexRouteImport } from './routes/practice/attachfile/index'
import { Route as PracticePostsIdRouteImport } from './routes/practice/posts/$id'
import { Route as PracticeBasicUseRefRouteImport } from './routes/practice/basic/useRef'
import { Route as PracticeBasicSuspenseRouteImport } from './routes/practice/basic/suspense'
import { Route as PracticeBasicModalRouteImport } from './routes/practice/basic/modal'
import { Route as PracticeBasicFormRouteImport } from './routes/practice/basic/form'

const PracticeRouteRoute = PracticeRouteRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticeFormSimpleRoute = PracticeFormSimpleRouteImport.update({
  id: '/form-simple',
  path: '/form-simple',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticeDashboardRoute = PracticeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticeCounterRoute = PracticeCounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticePostsIndexRoute = PracticePostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticeAttachfileIndexRoute = PracticeAttachfileIndexRouteImport.update({
  id: '/attachfile/',
  path: '/attachfile/',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticePostsIdRoute = PracticePostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticeBasicUseRefRoute = PracticeBasicUseRefRouteImport.update({
  id: '/basic/useRef',
  path: '/basic/useRef',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticeBasicSuspenseRoute = PracticeBasicSuspenseRouteImport.update({
  id: '/basic/suspense',
  path: '/basic/suspense',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticeBasicModalRoute = PracticeBasicModalRouteImport.update({
  id: '/basic/modal',
  path: '/basic/modal',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticeBasicFormRoute = PracticeBasicFormRouteImport.update({
  id: '/basic/form',
  path: '/basic/form',
  getParentRoute: () => PracticeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRouteRouteWithChildren
  '/practice/counter': typeof PracticeCounterRoute
  '/practice/dashboard': typeof PracticeDashboardRoute
  '/practice/form-simple': typeof PracticeFormSimpleRoute
  '/practice/': typeof PracticeIndexRoute
  '/practice/basic/form': typeof PracticeBasicFormRoute
  '/practice/basic/modal': typeof PracticeBasicModalRoute
  '/practice/basic/suspense': typeof PracticeBasicSuspenseRoute
  '/practice/basic/useRef': typeof PracticeBasicUseRefRoute
  '/practice/posts/$id': typeof PracticePostsIdRoute
  '/practice/attachfile/': typeof PracticeAttachfileIndexRoute
  '/practice/posts/': typeof PracticePostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practice/counter': typeof PracticeCounterRoute
  '/practice/dashboard': typeof PracticeDashboardRoute
  '/practice/form-simple': typeof PracticeFormSimpleRoute
  '/practice': typeof PracticeIndexRoute
  '/practice/basic/form': typeof PracticeBasicFormRoute
  '/practice/basic/modal': typeof PracticeBasicModalRoute
  '/practice/basic/suspense': typeof PracticeBasicSuspenseRoute
  '/practice/basic/useRef': typeof PracticeBasicUseRefRoute
  '/practice/posts/$id': typeof PracticePostsIdRoute
  '/practice/attachfile': typeof PracticeAttachfileIndexRoute
  '/practice/posts': typeof PracticePostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/practice': typeof PracticeRouteRouteWithChildren
  '/practice/counter': typeof PracticeCounterRoute
  '/practice/dashboard': typeof PracticeDashboardRoute
  '/practice/form-simple': typeof PracticeFormSimpleRoute
  '/practice/': typeof PracticeIndexRoute
  '/practice/basic/form': typeof PracticeBasicFormRoute
  '/practice/basic/modal': typeof PracticeBasicModalRoute
  '/practice/basic/suspense': typeof PracticeBasicSuspenseRoute
  '/practice/basic/useRef': typeof PracticeBasicUseRefRoute
  '/practice/posts/$id': typeof PracticePostsIdRoute
  '/practice/attachfile/': typeof PracticeAttachfileIndexRoute
  '/practice/posts/': typeof PracticePostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/practice'
    | '/practice/counter'
    | '/practice/dashboard'
    | '/practice/form-simple'
    | '/practice/'
    | '/practice/basic/form'
    | '/practice/basic/modal'
    | '/practice/basic/suspense'
    | '/practice/basic/useRef'
    | '/practice/posts/$id'
    | '/practice/attachfile/'
    | '/practice/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/practice/counter'
    | '/practice/dashboard'
    | '/practice/form-simple'
    | '/practice'
    | '/practice/basic/form'
    | '/practice/basic/modal'
    | '/practice/basic/suspense'
    | '/practice/basic/useRef'
    | '/practice/posts/$id'
    | '/practice/attachfile'
    | '/practice/posts'
  id:
    | '__root__'
    | '/'
    | '/practice'
    | '/practice/counter'
    | '/practice/dashboard'
    | '/practice/form-simple'
    | '/practice/'
    | '/practice/basic/form'
    | '/practice/basic/modal'
    | '/practice/basic/suspense'
    | '/practice/basic/useRef'
    | '/practice/posts/$id'
    | '/practice/attachfile/'
    | '/practice/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PracticeRouteRoute: typeof PracticeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/form-simple': {
      id: '/practice/form-simple'
      path: '/form-simple'
      fullPath: '/practice/form-simple'
      preLoaderRoute: typeof PracticeFormSimpleRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/dashboard': {
      id: '/practice/dashboard'
      path: '/dashboard'
      fullPath: '/practice/dashboard'
      preLoaderRoute: typeof PracticeDashboardRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/counter': {
      id: '/practice/counter'
      path: '/counter'
      fullPath: '/practice/counter'
      preLoaderRoute: typeof PracticeCounterRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/posts/': {
      id: '/practice/posts/'
      path: '/posts'
      fullPath: '/practice/posts/'
      preLoaderRoute: typeof PracticePostsIndexRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/attachfile/': {
      id: '/practice/attachfile/'
      path: '/attachfile'
      fullPath: '/practice/attachfile/'
      preLoaderRoute: typeof PracticeAttachfileIndexRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/posts/$id': {
      id: '/practice/posts/$id'
      path: '/posts/$id'
      fullPath: '/practice/posts/$id'
      preLoaderRoute: typeof PracticePostsIdRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/basic/useRef': {
      id: '/practice/basic/useRef'
      path: '/basic/useRef'
      fullPath: '/practice/basic/useRef'
      preLoaderRoute: typeof PracticeBasicUseRefRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/basic/suspense': {
      id: '/practice/basic/suspense'
      path: '/basic/suspense'
      fullPath: '/practice/basic/suspense'
      preLoaderRoute: typeof PracticeBasicSuspenseRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/basic/modal': {
      id: '/practice/basic/modal'
      path: '/basic/modal'
      fullPath: '/practice/basic/modal'
      preLoaderRoute: typeof PracticeBasicModalRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/basic/form': {
      id: '/practice/basic/form'
      path: '/basic/form'
      fullPath: '/practice/basic/form'
      preLoaderRoute: typeof PracticeBasicFormRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
  }
}

interface PracticeRouteRouteChildren {
  PracticeCounterRoute: typeof PracticeCounterRoute
  PracticeDashboardRoute: typeof PracticeDashboardRoute
  PracticeFormSimpleRoute: typeof PracticeFormSimpleRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  PracticeBasicFormRoute: typeof PracticeBasicFormRoute
  PracticeBasicModalRoute: typeof PracticeBasicModalRoute
  PracticeBasicSuspenseRoute: typeof PracticeBasicSuspenseRoute
  PracticeBasicUseRefRoute: typeof PracticeBasicUseRefRoute
  PracticePostsIdRoute: typeof PracticePostsIdRoute
  PracticeAttachfileIndexRoute: typeof PracticeAttachfileIndexRoute
  PracticePostsIndexRoute: typeof PracticePostsIndexRoute
}

const PracticeRouteRouteChildren: PracticeRouteRouteChildren = {
  PracticeCounterRoute: PracticeCounterRoute,
  PracticeDashboardRoute: PracticeDashboardRoute,
  PracticeFormSimpleRoute: PracticeFormSimpleRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  PracticeBasicFormRoute: PracticeBasicFormRoute,
  PracticeBasicModalRoute: PracticeBasicModalRoute,
  PracticeBasicSuspenseRoute: PracticeBasicSuspenseRoute,
  PracticeBasicUseRefRoute: PracticeBasicUseRefRoute,
  PracticePostsIdRoute: PracticePostsIdRoute,
  PracticeAttachfileIndexRoute: PracticeAttachfileIndexRoute,
  PracticePostsIndexRoute: PracticePostsIndexRoute,
}

const PracticeRouteRouteWithChildren = PracticeRouteRoute._addFileChildren(
  PracticeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PracticeRouteRoute: PracticeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
